server:
  port: 8081
  servlet:
    context-path: /api

spring:
  profiles:
    active: dev
  datasource:
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: db/changelog/db.changelog-main.yaml

cache:
  capacity: 10
  type: lru
