server:
  port: 8080

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/test
    username: postgres
    password: 12345678
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: false
  liquibase:
    change-log: db/changelog/db.changelog-main.yaml

cache:
  capacity: 10
  type: lru
