spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test?createDatabaseIfNotExist=true
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true